#!/bin/bash
if rpm -q hadoop | grep hadoop
then
echo "Hadoop Package is already installed"
else
echo "Hadoop Package is not installed"
echo "Installing Hadoop...."
sudo mkdir -p /tmp/Hadoop_repos
sudo wget -q -P /tmp/Hadoop_repos https://archive.apache.org/dist/hadoop/core/hadoop-1.2.1/hadoop-1.2.1-1.x86_64.rpm
sudo wget -q -P /tmp/Hadoop_repos https://repo.huaweicloud.com/java/jdk/8u171-b11/jdk-8u171-linux-x64.rpm
sudo rpm -ivh /tmp/Hadoop_repos/*.rpm
echo "Hadoop Installed Successfully"
fi
